version "3.3.2"

#include "zscript/ds_player.zs"
#include "zscript/ds_hud.zs"
#include "zscript/ds_deco.zs"
#include "zscript/ds_items.zs"
#include "zscript/ds_misc.zs"
#include "zscript/ds_effects.zs"
#include "zscript/ds_conversation.zs"
#include "zscript/ds_mainmenu.zs"